/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author minelli
 */
public class NewWindowP5 extends javax.swing.JFrame {

    /**
     * Creates new form ControladorMArco
     */
    public NewWindowP5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        idButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        pendingBadConsequenceView1 = new GUI.PendingBadConsequenceView();
        PendingBadConsequence = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Name");

        dniLabel.setText("DNI");

        idButton.setText("Identificacion");
        idButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IdPanelLayout = new javax.swing.GroupLayout(IdPanel);
        IdPanel.setLayout(IdPanelLayout);
        IdPanelLayout.setHorizontalGroup(
            IdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(IdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idButton)
                    .addComponent(dniLabel)
                    .addComponent(nameLabel)
                    .addComponent(exitButton)
                    .addComponent(pendingBadConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        IdPanelLayout.setVerticalGroup(
            IdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(idButton)
                .addGap(18, 18, 18)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dniLabel)
                .addGap(27, 27, 27)
                .addComponent(exitButton)
                .addGap(18, 18, 18)
                .addComponent(pendingBadConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        getContentPane().add(IdPanel, java.awt.BorderLayout.CENTER);

        PendingBadConsequence.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PendingBadConsequence, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idButtonActionPerformed
        nameLabel.setText("Ricardo");
        dniLabel.setText("k0987087");
    }//GEN-LAST:event_idButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IdPanel;
    private javax.swing.JPanel PendingBadConsequence;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton idButton;
    private javax.swing.JLabel nameLabel;
    private GUI.PendingBadConsequenceView pendingBadConsequenceView1;
    // End of variables declaration//GEN-END:variables
}
