
package GUI;

import napakalaki.BadConsequence;


/**
 *
 * @author minelli
 */

public class PendingBadConsequenceView extends javax.swing.JPanel {
    
    BadConsequence pendingBadModel;
    
    /*
    Sets the view of the Pending Bad Consequence
    Hides it if it is empty
    */
    public void setPendingBadConsequenceView (BadConsequence b)
    {
        pendingBadModel = b;
        
        if (b != null)
        {
            if (b.isEmpty())
                text.setText(" ");
            else
                text.setText(pendingBadModel.toString());
        }
        else
            text.setText(" ");
        
        repaint();
    }
    
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBorder(null);

        text.setEditable(false);
        text.setBackground(new java.awt.Color(0, 0, 0));
        text.setColumns(20);
        text.setForeground(new java.awt.Color(204, 0, 0));
        text.setLineWrap(true);
        text.setRows(2);
        text.setText("Current Bad Consequence");
        text.setWrapStyleWord(true);
        text.setBorder(null);
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
