
package GUI;

import napakalaki.Prize;


/**
 *
 * @author minelli
 */

public class PrizeView extends javax.swing.JPanel {
    
    private Prize prizeModel;
    
    public void setPrize (Prize p)
    {
        prizeModel = p;
        numLevels.setText(Integer.toString(prizeModel.getLevels()));
        numTreasures.setText(Integer.toString(prizeModel.getTreasures()));
        repaint();
    }

    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treasuresLabel = new javax.swing.JLabel();
        levelsLabel = new javax.swing.JLabel();
        numTreasures = new javax.swing.JLabel();
        numLevels = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 153, 0));
        setOpaque(false);

        treasuresLabel.setText("Treasures:");

        levelsLabel.setText("Levels:");

        numTreasures.setText("nt");

        numLevels.setText("nb");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(treasuresLabel)
                    .addComponent(levelsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numLevels)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(numTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treasuresLabel)
                    .addComponent(numTreasures))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelsLabel)
                    .addComponent(numLevels))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JLabel numLevels;
    private javax.swing.JLabel numTreasures;
    private javax.swing.JLabel treasuresLabel;
    // End of variables declaration//GEN-END:variables
}
